spring:
 application:
  name: turbine

turbine:
  aggregator:
    clusterConfig: WEB
  appConfig: web

server:
  port: 8084

eureka:
 client:
 serviceUrl:
  defaultZone: http://localhost:8761/eureka/
 instance:
      leaseRenewalIntervalInSeconds: 5
      instanceId : turbine

