spring:
  application:
   name: zuul
    
zuul:
 routes:
  accounts: 
   path: /accounts
   serviceId: accounts
  payments:
   path: /payments
   serviceId: payments
  payers:
   path: /payers
   serviceId: payments

# Tiene que ser TRUE para q Zuul funcione con serviceId
ribbon:
 eureka:
  enabled: true
  
server:
 port: 8080
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 5
      instanceId: zuul
      
# Logging settings.
# The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.

logging:
 level:
  ROOT: INFO
  org.springframework.cloud.netflix : DEBUG

